### ISSUE TITLE
Tham số phân trang https://api.kcoin.club/blocks

### ISSUE THREAD

**Issue by linhdmn** [nguyenkha/kcoin-blockchain#17]
Thưa thầy, tham số phân trang trong url https://api.kcoin.club/blocks đặt ở đâu trong request vậy ạ? Em xin cảm ơn

**Comment by nguyenkha** [comment]
Tham số query bạn https://api.kcoin.club/blocks?limit=100&offset=200&order=0

**Comment by nhatlinhdoan** [comment]
dạ e cảm ơn thầy ạ
