### ISSUE TITLE
Cách tạo unlockscript

### ISSUE THREAD

**Issue by tmpdat** [nguyenkha/kcoin-blockchain#18]
Thầy cho em hỏi, muốn tạo unlockscript để tạo giao dịch thì phải dùng hàm sign của thầy hay như thế nào ạ?

**Comment by nguyenkha** [comment]
Bạn tham khảo hàm `sign` và các hàm phụ thuộc để làm nhé, copy lại những phần cần thiết, không nhất thiết phải load lại toàn bộ các thứ không liên quan khác.
