### ISSUE TITLE
Sử dụng api generate-address không get được

### ISSUE THREAD

**Issue by hhhao79** [nguyenkha/kcoin-blockchain#4]
Em dùng api generate-address thì bị báo lỗi là:
Redirect from 'http://api.kcoin.club/generate-address' to 'https://api.kcoin.club/generate-address' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by hhhao79** [comment]
Thưa thầy Kha, thầy Khánh
Em dùng api generate-address thì bị báo lỗi là:
Redirect from 'http://api.kcoin.club/generate-address' to 'https://api.kcoin.club/generate-address' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by nguyenkha** [comment]
Chào bạn, 

API của blockchain bạn phải gọi từ server (dùng thư viện request hoặc thư viện khác) không gọi trực tiếp từ trình duyệt do mình thấy bạn bị lỗi CORS.

Ngoài ra để tạo địa chỉ bạn nên dùng dùng `generateAddress` ngay tại server bạn, không cần gọi đến blockchain vì blockchain không lưu thông tin lại cũng như giảm tải cho blockchain. API này trên blockchain được tạo ra nhằm mục đích ban đầu để các bạn có địa chỉ nhận KCoin dễ dàng hơn chứ không phải để gọi.

**Comment by thamtushinichi** [comment]
Bạn dùng thêm thư viện CORS trong web api của bạn để gọi rồi trả về lại giao diện web của bạn. 
Tham Khảo ở đây bạn : https://www.npmjs.com/package/cors
Bạn làm theo xem có gọi được không?

**Comment by nguyenkha** [comment]
> Bạn dùng thêm thư viện CORS trong web api của bạn để gọi rồi trả về lại giao diện web của bạn.
> Tham Khảo ở đây bạn : https://www.npmjs.com/package/cors
> Bạn làm theo xem có gọi được không?

Bạn gọi API blockchain từ server do bạn thì không có lỗi CORS. Lỗi này chỉ có trong trình duyệt.
